version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "newsletter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i08c2njn9tm"
s3_prefix = "newsletter"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
