---
AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:

  SubscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: subscribe
      Handler: main
      Runtime: go1.x
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /subscribe
            Method: get
            RequestParameters:
              - method.request.querystring.email:
                  Required: true

Outputs:

  Endpoint:
    Value:  !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"